apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd-aks-cicd-gitops-sample-app/webapp
    repoURL: https://github.com/tanvir0102/devops-engineering-learn-build-share.git
    targetRevision: HEAD
